codecov:
  require_ci_to_pass: yes
  token: 90a60cda-529c-45a6-bcfe-3529e06922eb
  ci:
    - travis
    - github actions

on:
  - push

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
